import APIMessage from "./APIMessage";
import Base from "./Base";
import MessageAttachment from "./MessageAttachment";
import MessageComponentInteractionCollector from "./MessageComponentInteractionCollector";
import ReactionCollector from "./ReactionCollector";
import Sticker from "./Sticker";
import Collection from "../util/Collection";
import MessageFlags from "../util/MessageFlags";
declare class Message extends Base {
    partial: false;
    channel: import("./Interfaces/TextBasedChannel");
    deleted: boolean;
    type: import("../Types").MessageType | null;
    system: boolean | null;
    content: string | null;
    author: import("./User") | null;
    pinned: boolean | null;
    tts: boolean | null;
    nonce: string | null;
    embeds: Array<import("./MessageEmbed")>;
    components: Array<import("./MessageActionRow")>;
    attachments: Collection<string, MessageAttachment>;
    stickers: Collection<string, Sticker>;
    createdTimestamp: number;
    editedTimestamp: number | null;
    reactions: Collection<string, import("./MessageReaction")>;
    mentions: import("./MessageMentions");
    webhookID: string | null;
    groupActivityApplication: import("./ClientApplication") | null;
    applicationID: string | null;
    activity: import("../Types").MessageActivity | null;
    member: import("./GuildMember");
    flags: Readonly<MessageFlags>;
    reference: import("../Types").MessageReference | null;
    interaction: import("../Types").MessageInteraction | null;
    constructor(client: import("../client/Client"), data: import("@amanda/discordtypings").MessageData, channel: import("./Interfaces/TextBasedChannel"));
    _patch(data: import("@amanda/discordtypings").MessageData): void;
    patch(data: import("@amanda/discordtypings").MessageData): this;
    get createdAt(): Date;
    get editedAt(): Date | null;
    get guild(): import("./Partial/PartialGuild") | null;
    get url(): string;
    get cleanContent(): string | null;
    createReactionCollector(filter: import("../Types").CollectorFilter<import("./MessageReaction")>, options?: import("../Types").ReactionCollectorOptions): ReactionCollector;
    awaitReactions(filter: import("../Types").CollectorFilter<import("./MessageReaction")>, options?: import("../Types").AwaitReactionsOptions): Promise<Collection<string, import("./MessageReaction")>>;
    createMessageComponentInteractionCollector(filter: import("../Types").CollectorFilter<import("./MessageComponentInteraction")>, options?: import("../Types").MessageComponentInteractionCollectorOptions): MessageComponentInteractionCollector;
    awaitMessageComponentInteraction(filter: import("../Types").CollectorFilter<import("./MessageComponentInteraction")>, time?: number): Promise<import("./MessageComponentInteraction")>;
    get editable(): boolean;
    get deletable(): boolean;
    get pinnable(): boolean;
    fetchReference(): Promise<Message>;
    get crosspostable(): boolean | null;
    edit(options: import("../Types").MessageEditOptions): Promise<void>;
    crosspost(): Promise<this>;
    pin(): Promise<this>;
    unpin(): Promise<this>;
    react(emoji: import("../Types").EmojiIdentifierResolvable): Promise<this>;
    clearReactions(): Promise<this>;
    delete(): Promise<this>;
    reply(options?: string | APIMessage | import("../Types").ReplyMessageOptions): Promise<Message>;
    fetch(): Promise<this>;
    fetchWebhook(): Promise<import("./Webhook")>;
    suppressEmbeds(suppress?: boolean): Promise<void>;
    removeAttachments(): Promise<void>;
    equals(message: Message, rawData: import("@amanda/discordtypings").MessageData): boolean;
    toString(): string | null;
    toJSON(): any;
}
export = Message;
