import TextBasedChannel from "./interfaces/TextBasedChannel";
import GuildChannel from "./GuildChannel";
import Constants from "../util/Constants";
declare class TextChannel extends GuildChannel implements TextBasedChannel {
    readonly lastPinAt: TextBasedChannel["lastPinAt"];
    lastPinTimestamp: TextBasedChannel["lastPinTimestamp"];
    lastMessageId: TextBasedChannel["lastMessageId"];
    readonly lastMessage: TextBasedChannel["lastMessage"];
    send: TextBasedChannel["send"];
    startTyping: TextBasedChannel["startTyping"];
    sendTyping: TextBasedChannel["sendTyping"];
    stopTyping: TextBasedChannel["stopTyping"];
    readonly typingCount: TextBasedChannel["typingCount"];
    readonly typing: TextBasedChannel["typing"];
    createMessageCollector: TextBasedChannel["createMessageCollector"];
    awaitMessages: TextBasedChannel["awaitMessages"];
    createMessageComponentInteractionCollector: TextBasedChannel["createMessageComponentInteractionCollector"];
    awaitMessageComponentInteraction: TextBasedChannel["awaitMessageComponentInteraction"];
    bulkDelete: TextBasedChannel["bulkDelete"];
    fetchMessage: TextBasedChannel["fetchMessage"];
    fetchMessages: TextBasedChannel["fetchMessages"];
    nsfw: boolean;
    rateLimitPerUser: number;
    topic: string;
    type: typeof Constants.ChannelTypes[0];
    static readonly default: typeof TextChannel;
    constructor(guild: import("./Partial/PartialGuild"), data: import("discord-typings").TextChannelData);
    toJSON(): import("discord-typings").TextChannelData;
    _patch(data: import("discord-typings").TextChannelData): void;
}
export = TextChannel;
